[workspace]

members = [
    "async-context",
    "bloom-core",
    "bloom-html",
    "bloom-server",
    "bloom-client",
    "bloom-client-example",
    "bloom-server-example",
    "bloom-rsx",
]

resolver = "2"
