[workspace]

members = [
    "async-context",
    "bloom-core",
    "bloom-html",
    "bloom-ssr",
    "bloom-client",
    "bloom-client-example",
    "bloom-server-example",
    "bloom-rsx",
    "bloom-hybrid",
]

resolver = "2"
